name: oq-321
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.8.9
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libexpat=2.6.4
  - libffi=3.4.2
  - libsodium=1.0.20
  - libsqlite=3.47.0
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.4.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=24.3.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.11.10
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pywin32=307
  - pyzmq=26.2.0
  - setuptools=75.6.0
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - pip:
      - alpha-shapes==1.1.1
      - asgiref==3.8.1
      - attrs==24.2.0
      - basemap==1.4.1
      - basemap-data==1.3.2
      - cartopy==0.24.1
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - django==4.2.16
      - docutils==0.21.2
      - fastjsonschema==2.21.1
      - fiona==1.10.1
      - fonttools==4.55.0
      - h5py==3.12.1
      - idna==3.10
      - ipython-genutils==0.2.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - llvmlite==0.43.0
      - matplotlib==3.7.0
      - nbformat==5.10.4
      - numba==0.60.0
      - numpy==1.26.4
      - openquake-engine==3.21.0
      - packaging==23.2
      - pandas==2.2.3
      - pillow==11.0.0
      - plotly==5.24.1
      - pyparsing==3.2.0
      - pyproj==3.6.1
      - pyshp==2.3.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - referencing==0.35.1
      - requests==2.32.3
      - rpds-py==0.22.1
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - shapely==2.0.6
      - sqlparse==0.5.2
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - toml==0.10.2
      - tzdata==2024.2
      - urllib3==2.2.3
